// Client-side initial offline seed data for standalone PWA deployment (GitHub Pages)

export const SEED_MEDICINES = [
  {
    id: "med-1",
    name: "Paracetamol 500mg",
    genericName: "Paracetamol / Acetaminophen",
    category: "Fever & Pain Relief",
    brandName: "Calpol 500 / Dolo 650",
    brandPrice: 38.00,
    genericPrice: 11.50,
    savingsPercent: 70,
    dosageForm: "Tablet",
    packSize: "10 Tablets",
    manufacturerGeneric: "Jan Aushadhi Kendra",
    inStock: true,
    composition: "Paracetamol IP 500mg",
    uses: "Mild to moderate fever, headache, body ache",
    elderlyNotes: "Safe for seniors. Do not exceed 2000mg per day if liver impaired."
  },
  {
    id: "med-2",
    name: "Metformin 500mg",
    genericName: "Metformin Hydrochloride",
    category: "Diabetes Management",
    brandName: "Glycomet 500 / Glucophage",
    brandPrice: 58.00,
    genericPrice: 14.00,
    savingsPercent: 76,
    dosageForm: "Tablet (Sustained Release)",
    packSize: "15 Tablets",
    manufacturerGeneric: "National Health Generic Supply",
    inStock: true,
    composition: "Metformin Hydrochloride IP 500mg",
    uses: "Type 2 Diabetes blood sugar control",
    elderlyNotes: "Take immediately after meals with plenty of water to prevent stomach upset."
  },
  {
    id: "med-3",
    name: "Telmisartan 40mg",
    genericName: "Telmisartan",
    category: "Blood Pressure & Heart",
    brandName: "Telma 40 / Micardis",
    brandPrice: 115.00,
    genericPrice: 28.00,
    savingsPercent: 75,
    dosageForm: "Tablet",
    packSize: "10 Tablets",
    manufacturerGeneric: "PMBJP Jan Aushadhi",
    inStock: true,
    composition: "Telmisartan IP 40mg",
    uses: "Hypertension (High BP), cardiovascular risk reduction",
    elderlyNotes: "Monitor BP regularly. Take at fixed morning time."
  },
  {
    id: "med-4",
    name: "Atorvastatin 10mg",
    genericName: "Atorvastatin Calcium",
    category: "Cholesterol & Heart",
    brandName: "Lipitor 10 / Atorva 10",
    brandPrice: 145.00,
    genericPrice: 32.00,
    savingsPercent: 78,
    dosageForm: "Tablet",
    packSize: "10 Tablets",
    manufacturerGeneric: "Jan Aushadhi Kendra",
    inStock: true,
    composition: "Atorvastatin IP 10mg",
    uses: "High cholesterol, prevention of stroke and heart attack",
    elderlyNotes: "Best taken at bedtime."
  },
  {
    id: "med-5",
    name: "Amlodipine 5mg",
    genericName: "Amlodipine Besylate",
    category: "Blood Pressure & Heart",
    brandName: "Norvasc 5 / Amlopres",
    brandPrice: 72.00,
    genericPrice: 12.00,
    savingsPercent: 83,
    dosageForm: "Tablet",
    packSize: "10 Tablets",
    manufacturerGeneric: "Jan Aushadhi Kendra",
    inStock: true,
    composition: "Amlodipine Besylate IP 5mg",
    uses: "High Blood Pressure and angina chest pain",
    elderlyNotes: "Watch for mild ankle swelling; elevate legs if sitting long periods."
  },
  {
    id: "med-6",
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    category: "Antacid & Gastric",
    brandName: "Omez 20 / Prilosec",
    brandPrice: 65.00,
    genericPrice: 16.50,
    savingsPercent: 74,
    dosageForm: "Capsule",
    packSize: "15 Capsules",
    manufacturerGeneric: "Generic Meds Network",
    inStock: true,
    composition: "Omeprazole IP 20mg",
    uses: "Acidity, heartburn, gastroesophageal reflux (GERD), ulcer healing",
    elderlyNotes: "Take 30 minutes before morning breakfast."
  },
  {
    id: "med-7",
    name: "Cetirizine 10mg",
    genericName: "Cetirizine Hydrochloride",
    category: "Allergy & Cold",
    brandName: "Zyrtec / Cetzine",
    brandPrice: 42.00,
    genericPrice: 9.00,
    savingsPercent: 78,
    dosageForm: "Tablet",
    packSize: "10 Tablets",
    manufacturerGeneric: "Jan Aushadhi Kendra",
    inStock: true,
    composition: "Cetirizine Hydrochloride IP 10mg",
    uses: "Sneezing, runny nose, allergic skin rash, itching",
    elderlyNotes: "May cause mild drowsiness; avoid driving or operating machinery."
  },
  {
    id: "med-8",
    name: "Calcium 500mg + Vitamin D3",
    genericName: "Calcium Carbonate + Cholecalciferol",
    category: "Bone & Joint Health",
    brandName: "Shelcal 500",
    brandPrice: 128.00,
    genericPrice: 35.00,
    savingsPercent: 72,
    dosageForm: "Tablet",
    packSize: "15 Tablets",
    manufacturerGeneric: "Jan Aushadhi Kendra",
    inStock: true,
    composition: "Elemental Calcium 500mg + Vitamin D3 250 IU",
    uses: "Osteoporosis, joint pain, bone strength in seniors",
    elderlyNotes: "Take with meals for optimal absorption."
  }
];

export const SEED_TESTS = [
  {
    id: "diag-1",
    name: "Senior Citizen Comprehensive Health Package",
    category: "Full Body Checkup",
    testsIncluded: ["HbA1c Blood Sugar", "Complete Hemogram (CBC)", "Lipid Profile (Cholesterol)", "Kidney Function (KFT)", "Liver Function (LFT)", "Urine Routine"],
    prepInstructions: "10-12 hours fasting required overnight. Water is allowed.",
    fastingRequired: true,
    avgMarketPrice: 2200,
    rosaDiscountPrice: 699,
    savingsPercent: 68,
    homeCollectionAvailable: true,
    homeCollectionFee: 0,
    turnaroundHours: 12
  },
  {
    id: "diag-2",
    name: "HbA1c Glycated Hemoglobin Test",
    category: "Diabetes",
    testsIncluded: ["HbA1c Average 3-Month Blood Glucose"],
    prepInstructions: "No fasting necessary. Can be given at any time of day.",
    fastingRequired: false,
    avgMarketPrice: 600,
    rosaDiscountPrice: 199,
    savingsPercent: 67,
    homeCollectionAvailable: true,
    homeCollectionFee: 0,
    turnaroundHours: 6
  },
  {
    id: "diag-3",
    name: "Lipid Profile (Complete Cholesterol)",
    category: "Heart & Vascular",
    testsIncluded: ["Total Cholesterol", "HDL Good Cholesterol", "LDL Bad Cholesterol", "Triglycerides", "VLDL"],
    prepInstructions: "10-12 hours overnight fasting mandatory.",
    fastingRequired: true,
    avgMarketPrice: 750,
    rosaDiscountPrice: 249,
    savingsPercent: 67,
    homeCollectionAvailable: true,
    homeCollectionFee: 0,
    turnaroundHours: 8
  },
  {
    id: "diag-4",
    name: "Complete Blood Count (CBC) with ESR",
    category: "Infection & Anemia",
    testsIncluded: ["Hemoglobin", "WBC Count", "Platelets", "RBC", "ESR (Inflammation Marker)"],
    prepInstructions: "No special preparation needed.",
    fastingRequired: false,
    avgMarketPrice: 450,
    rosaDiscountPrice: 149,
    savingsPercent: 67,
    homeCollectionAvailable: true,
    homeCollectionFee: 0,
    turnaroundHours: 6
  },
  {
    id: "diag-5",
    name: "Kidney Function Test (KFT / RFT)",
    category: "Kidney & Electrolytes",
    testsIncluded: ["Serum Creatinine", "Blood Urea", "Uric Acid", "BUN"],
    prepInstructions: "Drink normal water, avoid excessive meat diet 12 hours prior.",
    fastingRequired: false,
    avgMarketPrice: 800,
    rosaDiscountPrice: 260,
    savingsPercent: 67,
    homeCollectionAvailable: true,
    homeCollectionFee: 0,
    turnaroundHours: 8
  }
];

export const SEED_PRESCRIPTIONS = [
  {
    id: "rx-9821",
    rxNumber: "RX-ROSA-2026-9821",
    date: "2026-09-18",
    doctorName: "Dr. Rajeshwar Sharma",
    doctorReg: "MCI-48201",
    doctorSpecialty: "Geriatric Medicine",
    patientName: "Rameshwar Patel (Age: 68)",
    diagnosis: "Essential Hypertension & Mild Osteoarthritis",
    vitals: { bp: "138/86 mmHg", pulse: "72 bpm", weight: "66 kg", spO2: "98%" },
    medicines: [
      {
        name: "Telmisartan 40mg (Generic)",
        dosage: "1 tablet once daily",
        timing: "Morning after breakfast",
        duration: "30 Days",
        instructions: "Take with plain water. Monitor morning BP."
      },
      {
        name: "Calcium 500mg + Vitamin D3",
        dosage: "1 tablet once daily",
        timing: "After lunch",
        duration: "30 Days",
        instructions: "For knee joint support. Gentle 15-min morning walking recommended."
      }
    ],
    dietaryAdvice: "Low sodium salt diet. Drink at least 2 liters of warm water daily. Avoid excess fried foods.",
    followUpDate: "2026-10-18",
    qrCodeData: "AI-ROSA-VERIFIED:RX-9821:DR-SHARMA:TELMISARTAN-40:CALCIUM-500",
    audioAdvice: "Namaste Rameshwar ji. Dr. Sharma here. Please take your Telmisartan 40mg pill every morning after breakfast for your blood pressure. Take your Calcium pill after lunch. Avoid salty pickles and drink plenty of water."
  }
];
